# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python App

on:
  push:
  pull_request:
    types: [opened, reopened]

defaults:
  run:
    shell: bash

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruff
        run: pip install ruff
      - name: Ruff Check
        run: ruff check . --output-format=github
      - name: Ruff Format
        run: ruff format . --check

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install typing dependencies
        run: pip install mypy pytest -r requirements.txt
      - name: Mypy
        uses: liskin/gh-problem-matcher-wrap@v2
        with:
          linters: mypy
          run: mypy --show-column-numbers
